### ISSUE TITLE
Config file for bind

### ISSUE THREAD

**Issue by Snowmanko** [northox/dnssec-reverb#18]
Hi,
I don't fully understand situation that I am in.

Error on triggering command : `dnssec-reverb: cannot find $KEYZONE_CMD
`

dnssec-reverb.conf:
_keygen="$(which dnssec-keygen)"
signzone="$(which dnssec-signzone)"
key2ds="$(which dnssec-dsfromkey)"
checkzone="$(which named-checkzone)"
control="$(which rndc)"

KSK_PARAM="-n zone -a ECDSAP256SHA256 -f ksk"
ZSK_PARAM="-n zone -a ECDSAP256SHA256 "
SIGN_PARAM="-N increment"
DS_PARAM="-2"_

this early part of script should load config variables :
_CONF="dnssec-reverb.conf"
if [ -r "$DNSSEC_REVERB_CONF/$CONF" ]; then
        CONF="$DNSSEC_REVERB_CONF/$CONF"
elif [ -r "$DIR/$CONF" ]; then
        CONF="${DIR}/$CONF"
elif [ -r "/etc/$CONF" ]; then
        CONF="/etc/$CONF"
elif [ -r "/usr/local/etc/$CONF" ]; then
        CONF="/usr/local/etc/$CONF"
else
        Fatal "cannot find config file"
fi
. "$CONF"_

I suppose its done, but it gets Fatal right on first check.
`[ "$KEYGEN_CMD" = "" ] && Fatal "cannot find \$KEYZONE_CMD"`

There is no KEYGEN_CMD variable in default config. Am I missing something ?
I suppose "keygen" in config file should be KEYGEN_CMD no?

Thanks for clarifying. BR!

**Comment by northox** [comment]
My apology, I did not update the config files with the new variables - I always use the defaults already set in the script. Yes you are right. 

I can update those file later today if you can wait.

**Comment by Snowmanko** [comment]
I will send you PR.

**Comment by northox** [comment]
I added all vars that were needed or of interest to the users but not internal vars and those derived from MASTER_DIR - which was missing. I believe we have everything needed now. See #19. Can you confirm it's working for bind?

**Comment by northox** [comment]
Let me know if you need anything else. It's working in prob on OpenBSD w/ nsd so I appreciate test on Linux w/ bind.

**Comment by northox** [comment]
@Snowmanko any update?

**Comment by Snowmanko** [comment]
I dont have time right now to test it, will let you know ASAP.

**Comment by zenny** [comment]
> @Snowmanko any update?

@northox, nope. Tried with bind, but the -n option is not available with bind. Details are in https://github.com/northox/dnssec-reverb/issues/25.

Cheers,
/zenny

**Comment by zenny** [comment]
@northox bump

**Comment by northox** [comment]
I use and test dnssec-reverb on OpenBSD w/ NSD. Seems like you use a bind.
Please confirm this is addressed by the latest patch or provide your own I will close this issue in 2w if I have no news.
