### ISSUE TITLE
date is expecting reference file

### ISSUE THREAD

**Issue by hudecof** [northox/dnssec-reverb#23]
Hello,

the `date -r` is expecting reference file.
I have got error

```
root@ns01:/srv/dnssec# bash ./dnssec-reverb sign  64.57.2.in-addr.arpa
zone 64.57.2.in-addr.arpa is ok
date: 1685813368: No such file or directory
```

https://github.com/northox/dnssec-reverb/blob/9aa8e24d9aa2b880cfff35af933dc1e45a5693f0/dnssec-reverb#L163

regards
   hudecof

**Comment by hudecof** [comment]
should it be
```
 TT=$EXPIRE; date -d "@$TT" '+%Y/%m/%d %H:%M:%S' > "$KEYDIR/$ZSK.expire" 

```

**Comment by northox** [comment]
I use and test dnssec-reverb on OpenBSD. Seems like you use a Linux distro. 
Please confirm this is addressed by the latest patch  or provide patch. I will close this issue in 2w if I have no news.

**Comment by hudecof** [comment]
@northox yes, I'm using linux, Debian and Ubuntu.
I will test the new version and let you known.

**Comment by hudecof** [comment]
there is still `date -r` in code, which should fail.
But just `sign` command works, I need to test it a little bit more.

**Comment by northox** [comment]
The code detects the OS and use -d or -r depending if it’s Linux or BSD respectively.
