### ISSUE TITLE
generate DS line into the file

### ISSUE THREAD

**Issue by hudecof** [northox/dnssec-reverb#5]
I have several nested zones, like

- example.org
- test.example.org
- dev.example.org
- ...

It would be good to generate DS file for for the zone, so I could only do `$INCLUDE` into master zone.

**Comment by hudecof** [comment]
the `ldns-signzone` do not support `$INCLUDE` statement. The wrapper needs to be used 
- https://gist.github.com/jedisct1/2125545
- https://gist.github.com/baloo/2126876

**Comment by northox** [comment]
Merged with #7
