### ISSUE TITLE
 time value is invalid

### ISSUE THREAD

**Issue by ecutsa** [northox/dnssec-reverb#8]
hello
got an error on debian using your script

dnssec-signzone: fatal: time value 1540731882 is invalid

i read the docs and it is said:  If no end-time is specified, 30 days from the start time is used as a default. 
so maybe we can remove it ?

**Comment by northox** [comment]
Can you tell me which version of dnssec-signzone you have?

**Comment by northox** [comment]
Ok got it. It's a regretion on bind support from this commit: 56517b5956886cc656fba4bb02d7e65f93bc14d2

It works for nsd's dnssec tools but not dnssec-signzone.

@jfrioux

**Comment by northox** [comment]
@ecutsa can you confirm the latest commit fix your issue?

**Comment by northox** [comment]
@ecutsa we're actually looking at bumping this time-laps from 31 (full month) to 33 days to ensure everyone has a bit of time to manage any rollover problems (and for our monitoring tool to give us 2 days of alerting). 

@jfrioux you're on it?

**Comment by jfrioux** [comment]
@northox, yes. Will submit PR this weekend
